import { Container, Row, Col, Card, Button, Alert } from 'react-bootstrap';
import Head from 'next/head'
import TopNavBar from './topNavBar'

const Layout = ({ children }) => (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <TopNavBar />
        {/* <div className='sidebar'>
            <Alert>navigation</Alert>
        </div> */}
        <div className="" >
            <Row>
                <Col className="" md={12}>
                    {children}
                </Col>
            </Row>
        </div>
    </>
);

export default Layout;